### ISSUE TITLE
Is there any way to get the path of the selected item?

### ISSUE THREAD

**Issue by naveen-15697** [Frezc/react-finder#2]
Hi,
In my case, I need the the path of the selected item. That is, if the tree is like, `Parent1>Parent2>Child`, I need these three data. on selecting the `Child` element.
Let me know if there is any option for this.
Thanks in advance.

**Comment by Frezc** [comment]
You can check the internal util function to get the path.
```js
import { findInTree, atTreePath } from 'react-finder/lib/utils';

// in component
<ReactFinder
      dataSource={dataSource}
      // ... other props
      onSelect={(selectedKey) => {

            const nodeData = findInTree(dataSource, (node) => node.key === selectedKey, { withAppendData: true });
            if (nodeData) {
              const path = atTreePath(dataSource, nodeData.loc);
              // use path below
            }
      }}
/>
```

**Comment by naveen-15697** [comment]
@Frezc 
This is what exactly I needed!.
Thanks for the quick response!
